### ISSUE TITLE
Système d'inventaire

### ISSUE THREAD

**Issue by bLandais** [bLandais/projet-java#14]

**Comment by bLandais** [comment]
On peut accéder à l'inventaire mais les items n'ont pas tous été codés.

**Comment by bLandais** [comment]
_Pour le moment:_
* **FULL_HEAL** a été codé et testé 👍 
* **DEFENSE_INCREASE** a été codé, pas testé et pas implémenté dans le calcul des dégâts 👎 
* **ATTACK** a été codé, testé et bien implémenté dans le calcul des dégâts 👍 
* **RESET** a été codé, devrait théoriquement fonctionner mais pas testé 🙏 
* **SURPRISE** a été codé, devrait théoriquement fonctionner mais pas testé 🙏 

Voila !

**Comment by nsobczak** [comment]
Je testerai ça un jour :)
