### ISSUE TITLE
Numériser le diagramme UML

### ISSUE THREAD

**Issue by bLandais** [bLandais/projet-java#20]
_**Pour le rapport**_ 

* Avoir l'UML fait au propre ▶️ 🆗 
* Expliquer le fonctionnement global du jeu ▶️ **TODO**

**Comment by nsobczak** [comment]
@MFaideau devrait faire ça plutôt que d'aller acheter watch dog !

**Comment by bLandais** [comment]
D'où le ⚠ urgent ⚠ .... 😉

**Comment by nsobczak** [comment]
De ce que j'ai vu sur internet, avec _eclipse_ il faut installer des plugins pour générer l'uml à partir des sources.

**Comment by bLandais** [comment]
Merci, ca a l'air de fonctionner !
Tu as indirectement fait gagner du temps à Maxence 👍

**Comment by MFaideau** [comment]
Merci Nico , t'es vraiment un chic int ! (type) ;)
